### ISSUE TITLE
make install: LOCAL_PACK_PATH and LIB_PATH are not set

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-antenna-embedded#3]
Tested on a Linux system.

When running `make install` the libraries do not get actually installed: 
![image](https://user-images.githubusercontent.com/11096047/88266941-62bc6880-ccd0-11ea-8637-cf4cf3dc5c0c.png)

environment variables LOCAL_PACK_PATH and LIB_PATH are not set in the system, and they are not mentioned in the docs. I manually copied the libs to /usr/local/lib to make the example work, but what are correct values for these variables?

**Comment by simonerom** [comment]
I tried again with `make release` and `source ../scripts/env.sh` before running the examples and it actually works with referencing the libraries in the local build folder. No need to copy the libs into  /usr/local/lib

**Comment by raullenchai** [comment]
Need doc it somewhere for other ppl's reference.
